# Generated by Django 4.1.7 on 2023-03-10 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0002_rename_session_key_spotifytoken_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_in_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 23, 31, 53, 436334)),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.IntegerField(),
        ),
    ]
