# Generated by Django 4.1.7 on 2023-03-10 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0003_spotifytoken_expires_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_in_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 4, 35, 40, 810182, tzinfo=datetime.timezone.utc)),
        ),
    ]
