# Generated by Django 4.1.7 on 2023-03-11 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0004_alter_spotifytoken_expires_in_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spotifytoken',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='spotifytoken',
            name='username',
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='expires_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='session_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='uri',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='spotilists.spotifyuser'),
        ),
    ]
