# Generated by Django 4.1.7 on 2023-03-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0006_remove_spotifytoken_uri_spotifytoken_spotify_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='spotify_user_id',
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='spotify_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='spotilists.spotifyuser'),
        ),
    ]
