# Generated by Django 4.1.7 on 2023-03-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0007_remove_spotifytoken_spotify_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='spotify_user',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='spotilists.spotifyuser'),
        ),
    ]
