# Generated by Django 4.1.7 on 2023-03-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0008_alter_spotifytoken_spotify_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='spotify_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='spotilists.spotifyuser'),
        ),
    ]
