# Generated by Django 4.1.7 on 2023-03-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='session_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
