# Generated by Django 4.1.7 on 2023-04-02 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0013_spotifyuser_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='token_expires_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
