# Generated by Django 4.1.7 on 2023-04-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0014_spotifyuser_access_token_spotifyuser_refresh_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
    ]
