# Generated by Django 4.1.7 on 2023-04-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0016_post_playlist_name_post_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='playlist_songs',
        ),
    ]
