# Generated by Django 4.1.7 on 2023-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0017_remove_post_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='playlist_genre',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
