# Generated by Django 4.1.7 on 2023-04-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0018_post_playlist_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyuser',
            old_name='display_name',
            new_name='username',
        ),
    ]
