# Generated by Django 4.1.7 on 2023-04-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0019_rename_display_name_spotifyuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='spotify_display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
