# Generated by Django 4.1.7 on 2023-05-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0020_spotifyuser_spotify_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='profile_pic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
