# Generated by Django 4.1.7 on 2023-05-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0021_spotifyuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='profile_pic',
            field=models.CharField(default='default-profile-pic.jpg', max_length=100),
        ),
    ]
