# Generated by Django 4.1.7 on 2023-06-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0023_rename_tags_post_playlist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='playlist_items',
            field=models.CharField(default='', max_length=9999),
            preserve_default=False,
        ),
    ]
