# Generated by Django 4.1.7 on 2023-06-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0024_post_playlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='items',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
