# Generated by Django 4.1.7 on 2023-06-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0025_post_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='items',
            field=models.CharField(max_length=1500),
        ),
    ]
