# Generated by Django 4.1.7 on 2023-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0027_remove_post_items_alter_post_playlist_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='playlist_items',
            new_name='uris',
        ),
        migrations.AddField(
            model_name='post',
            name='track_uris',
            field=models.CharField(default='', max_length=6000),
            preserve_default=False,
        ),
    ]
