# Generated by Django 4.1.7 on 2023-08-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0028_rename_playlist_items_post_uris_post_track_uris'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_ids', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('no_playlists', models.IntegerField(blank=True, null=True)),
                ('no_tracks', models.IntegerField(blank=True, null=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotilists.spotifyuser')),
            ],
        ),
    ]
