# Generated by Django 4.1.7 on 2023-08-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0031_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='playlist_genre',
        ),
        migrations.RemoveField(
            model_name='post',
            name='playlist_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='playlist_tags',
        ),
        migrations.AddField(
            model_name='post',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spotilists.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='track_uris_no_available_markets',
            field=models.CharField(default=1, max_length=6000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='uris_no_available_markets',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
