# Generated by Django 4.1.7 on 2023-08-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotilists', '0033_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_tracks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
